from strategy.single_index_weekly import SingleIndexWeekly
from strategy.magnificent_seven_quarterly import MagnificentSevenQuarterly
from strategy.coefficient_of_variance import CoefficientOfVariance
strategy = CoefficientOfVariance()
strategy.load_dataset()