from enum import Enum

class BinanceStrategy(Enum):
    TRAILING_STOPLOSS = "TRAILING_STOPLOSS"
    TAKEPROFIT_MARKET = "TAKEPROFIT_MARKET"
    MARKET_MARKET = "MARKET_MARKET"
    TRAILING_STOPMARKET = "TRAILING_STOPMARKET"
    TRAILING_LIMIT = "TRAILING_LIMIT"
