from enum import Enum

class Strategy(Enum):
    BOLLINGER = "BOLLINGER"
    # BOLLINGER_WIDTH = "BOLLINGER_WIDTH"
    COEFFICIENT_OF_VARIANCE = "COEFFICIENT_OF_VARIANCE"
    # KURTOSIS = "KURTOSIS"
    MACD = "MACD"
    RSI = "RSI"
    # RSI_TO_COEV = "RSI_TO_COEV"
    STOCHASTIC_OSCILLATOR = "STOCHASTIC_OSCILLATOR"
    # STANDARD_DEVIATION = "STANDARD_DEVIATION"
    # SKEW = "SKEW" 
    # RANDOM = "RANDOM"
    # TECH_FACTOR_LOADING = "TECH_FACTOR_LOADING"
    # TECH_AI = "TECH_AI"
    # TECHNICAL = "TECHNICAL"
    # AVERAGE_RETURN = "AVERAGE_RETURN"
    # MOVING_AVERAGE = "MOVING_AVERAGE"
