from enum import Enum

class Strategy(Enum):
    COEFFICIENT_OF_VARIANCE = "COEFFICIENT_OF_VARIANCE"
    STANDARD_DEVIATION = "STANDARD_DEVIATION"
    SKEW = "SKEW"
    KURTOSIS = "KURTOSIS"    
    AVERAGE_RETURN = "AVERAGE_RETURN"
    MOVING_AVERAGE = "MOVING_AVERAGE"
    BOLLINGER = "BOLLINGER"
    BOLLINGER_WIDTH = "BOLLINGER_WIDTH"
    RSI = "RSI"
    MACD = "MACD"
    STOCHASTIC_OSCILLATOR = "STOCHASTIC_OSCILLATOR"
    RANDOM = "RANDOM"